name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prebuild the img
      run: ./run.sh only-build-img
    - name: run the script
      run: ./run.sh hello
    - uses: actions/upload-artifact@v4
      with:
        name: out
        path: ./wd-hello-2.12/
